# Generated by Django 5.0.6 on 2026-05-27 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_offset', models.IntegerField()),
                ('amount', models.FloatField()),
                ('category', models.CharField(default='Groceries', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PantryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('Produce', 'Produce'), ('Protein', 'Protein'), ('Dairy', 'Dairy'), ('Pantry', 'Pantry'), ('Frozen', 'Frozen'), ('Other', 'Other')], default='Other', max_length=20)),
                ('quantity', models.FloatField(default=1)),
                ('unit', models.CharField(default='pcs', max_length=20)),
                ('expires_at', models.DateField()),
                ('price_paid', models.FloatField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pantry', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet', models.CharField(default='any', max_length=20)),
                ('cuisines', models.JSONField(blank=True, default=list)),
                ('dislikes', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cuisine', models.CharField(default='Other', max_length=80)),
                ('minutes', models.IntegerField(default=20)),
                ('difficulty', models.CharField(default='Easy', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('ingredients', models.JSONField(blank=True, default=list)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('rating', models.FloatField(default=4.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
